### ISSUE TITLE
Compilation Problem

### ISSUE THREAD

**Issue by raphaelboukara** [PrecursorApp/om-i#5]
I have this alert during compilation:
mars 03, 2015 4:02:33 PM com.google.javascript.jscomp.LoggerErrorManager printSummary
AVERTISSEMENT: 1 error(s), 0 warning(s)
ERROR: JSC_DUPLICATE_INPUT. Duplicate input: file:/home/raphael/.m2/repository/org/clojure/google-closure-library/0.0-20140718-946a7d39/google-closure-library-0.0-20140718-946a7d39.jar!/goog/base.js at (unknown source) line (unknown line) : (unknown column)
 any ideas?

**Comment by raphaelboukara** [comment]
I tried with `[precursor/om-i "0.1.2" :exclusions [org.clojure/google-closure-library]]` in dependencies not working yet :(

**Comment by dwwoelfel** [comment]
Looks like this is happening b/c I'm requiring `goog` (to use `goog/now`) in core.cljs. Apparently goog doesn't need to be required (tested with advanced compilation). Pushing up the fix now, will release 0.1.4 with the fix.

**Comment by dwwoelfel** [comment]
Fixed in [0.1.4](https://github.com/PrecursorApp/om-i/tree/v0.1.4). Thanks for the report!

**Comment by raphaelboukara** [comment]
thank for you quick answer :)
