### ISSUE TITLE
Incorrect version in clojars

### ISSUE THREAD

**Issue by bostonou** [PrecursorApp/om-i#7]
Version [0.1.5 on clojars](https://clojars.org/precursor/om-i/versions/0.1.5) points to the [0.1.4 commit](https://github.com/PrecursorApp/om-i/commit/c93dfe1b87fc3166f5c484bf4a6846be139ac64c)

**Comment by dwwoelfel** [comment]
Huh, I wonder how that happened. I'll try again with 0.1.6.

**Comment by dwwoelfel** [comment]
Thanks for the report! I pushed up [0.1.6](https://github.com/PrecursorApp/om-i/tree/v0.1.6) to [clojars](https://clojars.org/precursor/om-i/versions/0.1.6).

**Comment by bostonou** [comment]
:+1: Thanks for the quick response
