### ISSUE TITLE
React 0.13 removes access to _rootNodeID

### ISSUE THREAD

**Issue by crofty** [PrecursorApp/om-i#9]
After updating my app to React 0.13 (Om 0.9.0) I got an error:

![localhost 3449 2015-07-16 17-21-08](https://cloud.githubusercontent.com/assets/12736/8728872/821bb574-2bdf-11e5-82bd-d1ce4c126153.png)

It looks like access to [_rootNodeID](https://facebook.github.io/react/blog/2015/03/10/react-v0.13.html#breaking-changes) was removed in 0.13.

**Comment by robert-stuttaford** [comment]
Bump! Do you have a plan for dealing with this, @dwwoelfel?

**Comment by dwwoelfel** [comment]
A similar problem is discussed here: https://github.com/omcljs/om/issues/332

I think it would work to use Brandon's suggestion of storing a unique id in the component's state. I'll try to investigate that later today, but patches are also welcome.

**Comment by dwwoelfel** [comment]
This should be fixed in 0.1.8. We just use the display name instead of depending on _rootNodeId.
